### ISSUE TITLE
Refactor the `resolveRef` logic be an external transformer like resolveEnv

### ISSUE THREAD

**Issue by ph** [elastic/go-ucfg#94]
When the library tries to make a template tag concrete it will do the following:

- Try to fetch the existing value in the YAML,
- Loop through the resolvers to find possible values.

This order is hardcoded and the first value found will be returned, it would be nice to be able to define the order where to fetch values including controlling the _resolveRef_.

**Comment by urso** [comment]
`resolveRef` is used by `resolve`. There are 3 kind of reference resolvers used in the given order:

1. resolve in config object itself
2. resolve from env-config object (configured via `Env` option)
3. apply custom resolvers

Some potential use-cases/scenarios for having resolve (order) configurable:

- disable resolving names from same config object or passed environments
- change resolver order, so to have a custom environment to overwrite keys in a config
- handle infinite loops if variable/reference expression is no DAG

We could introduce these changes:

1. update `Env` to register a resolver callback instead of adding the config object to the `options.env` environment. Note, the `env` based lookup still can reference keys being overwritten in the current config -> resolver context requires full config so to deal with variable references
2. add `Ref` options which adds in config resolver (behavior of resolveRef minus env lookup) to the resolve list

I'm not sure I'm happy about this proposal, though. These changes do not guarantee absence of infinite loops, but can be used to 'break' some loops in kind of a hacky way (by adding an custom/environment resolver before the Ref resolver). Plus, if not used correctly might lead to some weird inconsistencies (let's figure out in which environment a setting is resolved from) when resolving a variable. e.g.

config:
```
  a: 1
  b: ${a} 
```

environment:

```
a: 2
```

when evaluating this configuration with the `Env`-resolver being put before `Ref`-resolver we will get `a=1` and `b=2`.

The `Ref`-resolver (variable lookup in same config object) should always come first. `go-ucfg` should detect loops and depending on options should return an error or use the resolvers to find the value via `Env` or custom resolver.

How about:

- still change make `Env` to create a resolver callback (unifies Env and custom resolvers).
- have `go-ucfg` detect non-DAG expressions and:
  - error by default
  - use resolvers if `ResolveLoops` option is used. Error if no resolver can find the key.
  - (optional) add struct tag option to selectively enable `resolveLoops` in struct.  e.g. `struct { Password string `config:",resolveLoops" }`
- (optional?) Add setting to disable lookup of settings in config object itself `NoRef` (one can still add the config object via `Env` though)

**Comment by ph** [comment]
> The Ref-resolver (variable lookup in same config object) should always come first.

I am not sure this is always the desired behavior, in the context of beats I would have expected the following priority since our reference syntax doesn't allow users to define where we should fetch the values. 

1. CLI overwrites
2. Environments overwrites.
3. Keystore
4.  yaml node reference.

Maybe we should error when more than one resolvers returns a value? Maybe configurable in the resolver?

**Comment by ph** [comment]
Other than that +1 for the proposal

**Comment by urso** [comment]
The use-case asking for this was easily implemented in libbeat in a more application specific way. Closing for now. Feel free to reopen/comment if other use-cases arise.
